# fly.toml file generated for open-street-walk-backend on 2023-04-30T16:04:28+09:00

app = "open-street-walk-backend"
primary_region = "nrt"

[http_service]
  internal_port = 3000
  force_https = true

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
